apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-datasource
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Values.prometheus.name }}-service:{{ .Values.prometheus.service.port }}
        isDefault: true
