apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}-deployment
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.name }}
    spec:
      containers:
        - name: {{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.grafana.containerPort }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: datasource
          configMap:
            name: {{ .Values.grafana.name }}-datasource
        - name: dashboard-provider
          configMap:
            name: {{ .Values.grafana.name }}-dashboard-provider
        - name: dashboards
          configMap:
            name: {{ .Values.grafana.name }}-dashboard-json
