apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-config
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: '{{ include "cruduserchart.name" . }}'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['{{ include "cruduserchart.name" . }}-service:{{ .Values.service.port }}']
      - job_name: 'nginx-ingress'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['nginx-ingress-nginx-controller.m.svc.cluster.local:10254']
      - job_name: 'kubelet-cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: /metrics/cadvisor
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      {{- if .Values.postgresExporter.enabled }}
      - job_name: '{{ .Values.postgresExporter.name }}'
        static_configs:
          - targets: ['{{ .Values.postgresExporter.name }}:{{ .Values.postgresExporter.service.port }}']
      {{- end }}
