apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}-service
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      targetPort: {{ .Values.prometheus.containerPort }}
      port: {{ .Values.prometheus.service.port }}
  selector:
    app: {{ .Values.prometheus.name }}
