apiVersion: v1
kind: Secret
metadata:
  name: {{- include "cruduserchart.name" . | indent 2 }}-secret
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER_PASSWORD: {{ .Values.secret.datasourcePassword | quote }}