apiVersion: v1
kind: Service
metadata:
  name: {{- include "cruduserchart.name" . | indent 2 }}-service
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      targetPort: {{ .Values.deployment.containerPort }}
      port: {{ .Values.service.port }}
  selector:
    {{- include "cruduserchart.selectorLabels" . | nindent 4 }}
