apiVersion: v1
kind: Service
metadata:
  name: {{- include "cruduserchart.name" . | indent 2 }}Service
  labels:
    {{- include "cruduserchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      protocol: TCP
  selector:
    {{- include "cruduserchart.selectorLabels" . | nindent 4 }}
